### ISSUE TITLE
Support the 'context' argument to the GH status API

### ISSUE THREAD

**Issue by rouge8** [litl/leeroy#40]
GitHub supports statuses from [multiple tools on the same commit](https://github.com/blog/1935-see-results-from-all-pull-request-status-checks) by [including a `context` in the status](https://developer.github.com/v3/repos/statuses/#create-a-status).

If would be nice to be able to use that with leeroy, perhaps with a default context of `None` in the settings (so that it's backwards compatible) and the option to set the context per job.

**Comment by rouge8** [comment]
I should have time to implement/test this within the next week or so, adding a `CONTEXT`/`context` setting to `settings.py`/per-job.

**Comment by joeshaw** [comment]
I set it now to `leeroy/jenkins` but it'd be easy to add it to the config.

**Comment by webmaven** [comment]
So, can the issue be closed?

**Comment by joeshaw** [comment]
If the current implementation is fine for @rouge8, then yes.  But I think he was asking for something more customizable: the ability to set the context per job.

**Comment by rouge8** [comment]
Yup, per-job context was the goal.

**Comment by webmaven** [comment]
@rouge8 did you want to contribute a PR?

**Comment by rouge8** [comment]
I haven't had time lately and probably won't in the immediate future. :/
