### ISSUE TITLE
Version 0.2.2 is way out of date

### ISSUE THREAD

**Issue by adzellman** [litl/leeroy#44]
Version 0.2.2 on pip is more than two years old. The latest bug fixes and features are not available if the user installs leeroy using the directions in the README.

**Comment by joeshaw** [comment]
You're right, I will try to make a new release this week.

**Comment by adzellman** [comment]
I used the following installation command to work around this issue:
```
sudo pip install --upgrade git+https://github.com/litl/leeroy.git@master
```
Perhaps it should be added to the README.

**Comment by joeshaw** [comment]
I haven't forgotten about this, but I just pushed 177658f and I want to test it in deployment for a little bit before I cut a release.

**Comment by joeshaw** [comment]
ok, leeroy 0.3.0 released: https://pypi.python.org/pypi/leeroy/0.3.0

**Comment by adzellman** [comment]
@joeshaw Thanks!
